export interface ItemsOrder {
    id: number,
    order_id: number,
    product_id: string,
    description_product: string,
    street: string,
    module: string,
    height: string,
    position: string,
    quantity_lack: number,
    quantity_total: number,
    unity: string,
    ean: string,
    color_tag: string,
    code_tag: string,
    confirmTag: number,
    timer_start: undefined,
    timer_end: undefined,
    chronometer: undefined
}

//                         "id": 1,
//                         "order_id": 1,
//                         "product_id": "1",
//                         "description_product": "ÁLCOOL GEL MATA GERME 70% 300ML",
//                         "street": "03",
//                         "module": "11",
//                         "height": "05",
//                         "position": "12",
//                         "quantity_lack": 3,
//                         "quantity_total": 3,
//                         "unity": "UN",
//                         "ean": "7896509976556",
//                         "color_tag": "verde",
//                         "code_tag": "051",
//                         "confirmTag": 0,
//                         "price": 10.33,
//                         "timer_start": "",
//                         "timer_end": null,
//                         "chronometer": null
